### ISSUE TITLE
Switching doesn't work

### ISSUE THREAD

**Issue by AtomicBlom** [McJty/CombatHelp#1]
Was just watching Vaygrim's stream and we discussed the mod not working as designed for him on FC2.

We suspect that it might be related to the fact getSlotFor uses stackEqualExact, so if the shield is damaged it doesn't pick up as a valid shield.

Sorry to say I don't have exact version number he's using handy.

**Comment by McJty** [comment]
Ok, stupid bug. I'll fix that today

**Comment by McJty** [comment]
Fixed in next release
