### ISSUE TITLE
PlayerInventoryStore capability not registered

### ISSUE THREAD

**Issue by squeek502** [McJty/CombatHelp#4]
Full details here: https://github.com/squeek502/SpiceOfLife/issues/91

The important bit:

> @McJty and I actually made the exact same mistake, and therefore our wires are getting crossed.
> 
> Neither of us are registering our capabilities with `CapabilityManager.INSTANCE`, which means that our `@CapabilityInject` annotated fields never get populated, which means that we're sending `null` to `getCapability`, which then 'succeeds' the conditional and we return our capabilities to eachother incorrectly.

The fix commit for reference: https://github.com/squeek502/SpiceOfLife/commit/06ad04c90f5ba0563c69944aac09a0c66d8b8d5e

**Comment by McJty** [comment]
Thanks for the advice! I forgot this indeed. Fixed for next release
